name: Release Tauri App

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # 仅在创建 vX.X.X 格式的 tag 时触发

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: 'Release ${{ github.ref_name }}'
          draft: false
          prerelease: false

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 根据你的项目选择合适的 Node.js 版本

      # 根据你的包管理器选择，这里以 pnpm 为例
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 在 Windows 上需要安装 WebView2
      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc
          
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.id }}
          